### ISSUE TITLE
minor issues with parameter docs

### ISSUE THREAD

**Issue by mhinsch** [JIC-CSB/kilombo#29]
missing:

turn_rate (should also be turnRate to stay consistent)
speed

unclear:

timeStep (after looking through the code I realized that this is actually the integration step and thus belongs into the 'simulation' category)

typos:

The names of the noise parameter are actually camelCase.

**Comment by fjansson** [comment]
Fixed docs, changed turn_rate -> turnRate.
Commit f9f8386f7f33b00
