### ISSUE TITLE
Trouble finding dependencies while installing

### ISSUE THREAD

**Issue by joemac875** [JIC-CSB/kilombo#43]
Hi all,

I'm trying to install Kilombo on my Mac running High Sierra. I made it to the `sudo make install` command, but run into this problem:

```
[  3%] Building C object src/CMakeFiles/headless.dir/skilobot.c.o
/Users/joemacinnes/kilobots/kilombo/src/skilobot.c:8:10: fatal error: 
      'jansson.h' file not found
#include <jansson.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/headless.dir/skilobot.c.o] Error 1
make[1]: *** [src/CMakeFiles/headless.dir/all] Error 2
make: *** [all] Error 2
```

I definitely installed the jansson library using Brew, but it seems like it can't find it. Any ideas on how I should solve this? Thanks!

**Comment by mhinsch** [comment]
I'm not a mac person, so I'm not sure how well brew and CMake usually cooperate. What you could try as a quick fix would be to add the directory your jansson headers ended up in to the C_INCLUDE_PATH environment variable. So, in the shell before running ``make install`` you do:
``export C_INCLUDE_PATH=$C_INCLUDE_PATH:DIR_OF_YOUR_JANSSON_HEADERS``

**Comment by joemac875** [comment]
Thanks for the quick response! I tried 

`export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/local/Cellar/jansson/2.10/`

but I still get the same error. `/usr/local/Cellar/jansson/2.10/` is what was returned after running `brew info jansson`

**Comment by mhinsch** [comment]
That's most probably not the correct directory. I'm not sure how brew handles include file installation, but my guess would be that ``jansson.h`` ended up in ``/usr/local/include`` or ``/usr/local/include/jansson``. The easiest (if somewhat brute-force) way to find out would be to use find:

```
cd /usr/local
find . -name jansson.h
```

**Comment by fjansson** [comment]
I just tested compiling on my mac, and for me it works.  For me, jansson is installed by brew in /usr/local/Cellar/jansson/2.10 and there are symlinks in /usr/local/lib and /usr/local/include. So it should be enough for the compiler to look in the /usr/local/ directories.   

In my `.bash_profile` I have:
```
export C_INCLUDE_PATH=/usr/local/include/:$C_INCLUDE_PATH
export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
```

Note that in our readme, the two first lines almost look like a single line, this is wrong. Also note that after editing .bashrc, you need to either launch a new terminal or `source ~/.bashrc` for the settings to take effect.

**Comment by joemac875** [comment]
I can confirm that `/usr/local/include` does contain `jansson.h`. However, when I did `export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/local/include/`, the problem persists.

My `.bash_profile`  has

```
export C_INCLUDE_PATH=/usr/local/include/:$C_INCLUDE_PATH
export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
```

as well.

**Comment by stanmaree** [comment]
hi Joe,

it seems that in your case the linking in brew did not go OK.

try 

brew link jansson

or, to rebuild the links

brew unlink jansson && brew link jansson

after that it should be found automatically.

Hope this helps,

best, Stan

**Comment by joemac875** [comment]
Thanks, Stan. I tried unlinking and relinking, but to no avail.

I know my C compiler can see `jansson.h` because if I try to compile 

```
#include <jansson.h>
  
int main(){
return 0;
}
```

I don't get any errors. When I try to compile something with a fake header, like 
```
#include <nonexistent.h>
  
int main(){
return 0;
}
```
Then I get 

```
test.c:1:10: fatal error: 'nonexistent.h' file not found
#include <nonexistent.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

My confusion is how does `gcc test.c` work but not `sudo make install` for Kilombo, if both are using GCC and looking for `jansson.h`?

**Comment by mhinsch** [comment]
I just realized that since you run the compilation sudo your environment variables (including C_INCLUDE_PATH) won't be set. There are basically three solutions:

- run ``sudo -E make install`` - this will preserve the value of env variables
- run ``make`` as regular user and ``sudo make install`` afterwards
- change the value of C_INCLUDE_PATH system-wide (no idea how to do that on a mac, though)

**Comment by joemac875** [comment]
This worked! Thank you all for your help and quick responses.
