### ISSUE TITLE
About the boundary of arean

### ISSUE THREAD

**Issue by Hi-Ryan** [JIC-CSB/kilombo#46]
Can we restrict the motion area of kilobot to a bounded area?

**Comment by mhinsch** [comment]
Yes, you can add physical obstacles (see documentation) to your arena. If you define then accordingly they can act as a boundary.

**Comment by Hi-Ryan** [comment]
Can you give me an example code for adding obstacles? I don't know how to use the 'callback_obstacles' function. Thanks for your help.

**Comment by mhinsch** [comment]
This function provides the callback to set a circular barrier:

int16_t circle_barrier(double x, double y, double * dx, double * dy)
        {
        double d = sqrt(x*x + y*y);

        if (d < 447.0)
                return 0;

        *dx = -x/d;
        *dy = -y/d;

        return 1;
        }


To tell the simulator to use it you have to set the call back in main like this:

SET_CALLBACK(obstacles, circle_barrier);





On Mon, Apr 30, 2018 at 01:29:55AM -0700, Hi-Ryan wrote:
> Can you give me an example code for adding obstacles? I don't know how to use the 'callback_obstacles' function. Thanks for your help.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/JIC-CSB/kilombo/issues/46#issuecomment-385338769

-- 

Dr Martin Hinsch

hinsch.martin@gmail.com
+44 7481898157

**Comment by Hi-Ryan** [comment]
Thank you!!
